### ISSUE TITLE
Composer repository objects are sorted differently when in an array or an object

### ISSUE THREAD

**Issue by fredden** [localheinz/json-normalizer#871]
When using `composer normalize` version `2.30.2`, the action taken on the contents of the `repositories` property is not consistent.

#### Steps required to reproduce the problem

1. Given the following `composer.json` (where 'repositories' is an array):

   ```json
   {
     "repositories": [
       {
         "url": "http://packages.example.com",
         "only": [ "example/*" ],
         "type": "composer"
       }
     ]
   }
   ```

1.  `composer normalize` results in:

   ```json
   {
     "repositories": [
       {
         "type": "composer",
         "url": "http://packages.example.com",
         "only": [
           "example/*"
         ]
       }
     ]
   }
   ```

However...

1. Given the following `composer.json` (where 'repositories' is an object):

   ```json
   {
     "repositories": {
       "example": {
         "url": "http://packages.example.com",
         "only": [ "example/*" ],
         "type": "composer"
       }
     }
   }
   ```

1.  `composer normalize` results in:

   ```json
   {
     "repositories": {
       "example": {
         "only": [
           "example/*"
         ],
         "type": "composer",
         "url": "http://packages.example.com"
       }
     }
   }
   ```

#### Expected Result

- Key order is consistent for repository objects.

#### Actual Result

- Key order is inconsistent.
  - Arrays are sorted: `type`, `url`, `only`
  - Objects are sorted: `only`, `type`, `url`

**Comment by localheinz** [comment]
Thank you for reporting, @fredden!
